apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app
      component: frontend
  template:
    metadata:
      labels:
        name: app
        component: frontend
    spec:
      containers:
        - name: app
          image: paulczar/gb-frontend:v5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 80