apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
       name: mongo
       component: database
spec:
  selector:
    matchLabels:
       name: mongo
       component: database
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
        component: database
    spec:
      containers:
        - name: mongo
          image: mongo:4.2
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-volume
          args:
            - --bind_ip
            - 0.0.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-persistent-volume